// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoFinanceiro.Data;

#nullable disable

namespace ProjetoFinanceiro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoFinanceiro.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PainelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PainelId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProjetoFinanceiro.Models.Movimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PainelId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoMovimento")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PainelId");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("ProjetoFinanceiro.Models.Painel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Paineis");
                });

            modelBuilder.Entity("ProjetoFinanceiro.Models.Categoria", b =>
                {
                    b.HasOne("ProjetoFinanceiro.Models.Painel", "Painel")
                        .WithMany("Categoria")
                        .HasForeignKey("PainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painel");
                });

            modelBuilder.Entity("ProjetoFinanceiro.Models.Movimento", b =>
                {
                    b.HasOne("ProjetoFinanceiro.Models.Categoria", "Categoria")
                        .WithMany("Movimentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoFinanceiro.Models.Painel", "Painel")
                        .WithMany("Movimentos")
                        .HasForeignKey("PainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Painel");
                });

            modelBuilder.Entity("ProjetoFinanceiro.Models.Categoria", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("ProjetoFinanceiro.Models.Painel", b =>
                {
                    b.Navigation("Categoria");

                    b.Navigation("Movimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
